export const AUTH_ERROR_CODES = {
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  INVALID_TOKEN: "INVALID_TOKEN",
  SESSION_EXPIRED: "SESSION_EXPIRED",
  SESSION_REVOKED: "SESSION_REVOKED",
  ACCESS_REVOKED: "ACCESS_REVOKED",
  USER_BLOCKED: "USER_BLOCKED",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  OTP_INVALID: "OTP_INVALID",
  OTP_EXPIRED: "OTP_EXPIRED",
  LOGIN_FAILED: "LOGIN_FAILED",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  MISSING_OTP: "MISSING_OTP",
  PHONE_NOT_FOUND: "PHONE_NOT_FOUND",
} as const;

export type AuthErrorCode = (typeof AUTH_ERROR_CODES)[keyof typeof AUTH_ERROR_CODES];
